name: Upload Docker image and run test

on:
  pull_request:
    branches:
      - main

jobs:
  buildandupload:
    name: Upload image to dockerhub
    uses: supratikiisc/CICD_Assignment/.github/workflows/build_docker_push_image.yml@main
    secrets: inherit
  pullandrun:
    name: Pull image and run test
    needs: buildandupload
    if: needs.buildandupload.result == 'success'
    uses: supratikiisc/CICD_Assignment/.github/workflows/pull_and_run_docker_image.yml@main
    secrets: inherit
