name: Pull and run Docker Image

on:
  workflow_run:
    workflows: ["Build and Push Docker Image To Dockerhub"]
    types:
      - completed
    branches:
      - main

jobs:
  pull-and-run-image:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: |
          docker pull supratikb/cicd_assignment:pr-${{ github.event.workflow_run.event.pull_request.number }}

      - name: Run Docker image and check score
        run: |
          OUTPUT=$(docker run --rm supratikb/cicd_assignment:pr-${{ github.event.workflow_run.event.pull_request.number }} | tail -n 1)
          echo "Model score:"
          echo "$OUTPUT"
          if [[ `echo "$OUTPUT 0.35" | awk '{print ($1 < $2)}'` == 1 ]]; then echo "Insufficient Accuracy" && exit 1; else echo "Score is above 0.35, success!"; fi
